### ISSUE TITLE
Keyserver problem when running two program instances.

### ISSUE THREAD

**Issue by andreimacavei** [andreimacavei/geysigning#2]
If you want to test the actual key transfer, open 2 instances of Geysign, in one select a key to be signed on the "Keys" tab and click 'Next' 2 times. In the other window open "Get Keys" tab and type or scan the fingerprint of the key selected in first instance. 
On the second window it now should display the key that was imported along with its fingerprint.
On my computer this hangs until I stop the server in the first window (press back button) and then the key is displayed.

**Comment by muelli** [comment]
Is this actually still an issue?

**Comment by andreimacavei** [comment]
I've tested it now and the problem was fixed. I will close this issue
